# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "S03-WF3: GH Issue Opened"

on:
  issues:
    types: [opened]

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        run: echo "${{ toJson(github.event.issue) }}"
